services:

  - type: web
    name: teyzus-backend
    runtime: python

    buildCommand: pip install -r backend/requirements.txt

    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT

    envVars:
      - key: APP_NAME
        value: TEYZUS

      - key: VERSION
        value: 1.0


  - type: worker
    name: teyzus-bot
    runtime: python

    buildCommand: pip install -r bot/requirements.txt

    startCommand: python bot/main.py

    envVars:
      - key: APP_NAME
        value: TEYZUS
